name: Aomen
on:
  workflow_dispatch:
  repository_dispatch:
    types: [webhook]
  # schedule:
   #  - cron: '1 2,4,6,8,11,13,16,22 * * *'
     

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout actions
      uses: actions/checkout@v2
    - name: Set python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade requests
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 'aomen'
      run: python aomen.py
      
    - name: Get current date
      id: today
      run: echo "::set-output name=date::$(date +'%Y%m%d%H')"
        
    - name: Push to Repo
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'aomen'
        destination_repo: 'Rokate/imagebackup'
        user_email: 'rokate1990@gmail.com'
        user_name: 'Rokate'
        commit_message: ${{ steps.today.outputs.date }}-update
  
