name: Aomen

on:
  workflow_dispatch:
  schedule:
    - cron: '10 1,3,5,7,9,11,13,15,17,19,21,23 * * *'
 
    
env: # 设置环境变量
  TZ: Asia/Shanghai
  
jobs:
  AOMEN:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - name: checkout actions
      uses: actions/checkout@v2
    - name: Set python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: python -m pip install --upgrade requests
      
    - name: 'aomen'
      run: python aomen.py
      
    - name: Get current date
      id: today
      run: echo "::set-output name=date::$(date +'%Y%m%d')"
        
    - name: Push to Repo
      uses: dmnemec/copy_file_to_another_repo_action@v1.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'aomen'
        destination_repo: 'Rokate/imagebackup'
        user_email: 'rokate1990@gmail.com'
        user_name: 'Rokate'
        commit_message: ${{ steps.today.outputs.date }}-update
  
